# Generated by Django 3.2.9 on 2022-03-11 00:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogEconomia', '0002_alter_blog_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Contenido',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
    ]
