# Generated by Django 3.2.9 on 2022-03-11 14:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogEconomia', '0003_alter_blog_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1000),
        ),
    ]
