# Generated by Django 3.2.9 on 2022-03-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuentasApp', '0006_auto_20220310_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='email',
            field=models.EmailField(blank=True, max_length=25, null=True),
        ),
    ]
