# Generated by Django 3.2.9 on 2022-03-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CuentasApp', '0007_avatar_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
